export const API_DOGS_LIST_REQUEST = 'API_DOGS_LIST_REQUEST';
export const API_DOGS_LIST_SUCCESS = 'API_DOGS_LIST_SUCCESS';
export const API_DOGS_RANDOM_REQUEST = 'API_DOGS_RANDOM_REQUEST';
export const API_DOGS_RANDOM_SUCCESS = 'API_DOGS_RANDOM_SUCCESS';
export const API_DOGS_FAILURE = 'API_DOGS_FAILURE';
export const API_DOGS_SELECT_BREED = 'API_DOGS_SELECT_BREED';
export const API_DOGS_SELECTED_LIST_SUCCESS = 'API_DOGS_SELECTED_LIST_SUCCESS';
